### PR TITLE
Allow offset to accept multiple polygons, and some build cleanup

### PR DESCRIPTION
**Pull request by jsadusk**
This PR includes two small changes. 

The first is a minor build cleanup. I change the build.rs to use cc::Build instead of cmake. This builds faster than cmake and removes a dependency on an external build tool. In addition, I cleaned up signed/unsigned comparison warnings in wrapper.cpp that are now surfaced. I opted not to clean up clipper.cpp because that is external code.

Second, I modified the interface to offset to allow a Polygons list. I have a parallel PR almost ready for geo-clipper that uses this to provide offsetting for geo::MultiPolygon.

### CODE REVIEW

**Comment by jsadusk** [comment]
I didn't update a test, will reopen when that's fixed

**Comment by lelongg** [comment]
Thanks for this PR.
I have a bunch of new warnings that I do not get on master, do you have them too ?
Any idea how to get rid of these ?

```
warning: In file included from /nix/store/b3zsk4ihlpiimv3vff86bb5bxghgdzb9-gcc-9.2.0/include/c++/9.2.0/x86_64-unknown-linux-gnu/bits/os_defines.h:39,
warning:                  from /nix/store/b3zsk4ihlpiimv3vff86bb5bxghgdzb9-gcc-9.2.0/include/c++/9.2.0/x86_64-unknown-linux-gnu/bits/c++config.h:524,
warning:                  from /nix/store/b3zsk4ihlpiimv3vff86bb5bxghgdzb9-gcc-9.2.0/include/c++/9.2.0/bits/stl_algobase.h:59,
warning:                  from /nix/store/b3zsk4ihlpiimv3vff86bb5bxghgdzb9-gcc-9.2.0/include/c++/9.2.0/vector:60,
warning:                  from clipper/clipper.hpp:52,
warning:                  from clipper/clipper.cpp:41:
warning: /nix/store/fwpn2f7a4iqszyydw7ag61zlnp6xk5d3-glibc-2.30-dev/include/features.h:382:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
warning:   382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
warning:       |    ^~~~~~~
warning: clipper/clipper.cpp: In function ‘ClipperLib::Int128 ClipperLib::Int128Mul(ClipperLib::long64, ClipperLib::long64)’:
warning: clipper/clipper.cpp:376:22: warning: implicitly-declared ‘constexpr ClipperLib::Int128& ClipperLib::Int128::operator=(const ClipperLib::Int128&)’ is deprecated [-Wdeprecated-copy]
warning:   376 |   if (negate) tmp = -tmp;
warning:       |                      ^~~
warning: clipper/clipper.cpp:264:5: note: because ‘ClipperLib::Int128’ has user-provided ‘ClipperLib::Int128::Int128(const ClipperLib::Int128&)’
warning:   264 |     Int128(const Int128 &val): lo(val.lo), hi(val.hi){}
warning:       |     ^~~~~~
warning: clipper/clipper.cpp: In function ‘void ClipperLib::InitEdge(ClipperLib::TEdge*, ClipperLib::TEdge*, ClipperLib::TEdge*, const ClipperLib::IntPoint&)’:
warning: clipper/clipper.cpp:721:34: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct ClipperLib::TEdge’; use assignment or value-initialization instead [-Wclass-memaccess]
warning:   721 |   std::memset(e, 0, sizeof(TEdge));
warning:       |                                  ^
warning: clipper/clipper.cpp:66:8: note: ‘struct ClipperLib::TEdge’ declared here
warning:    66 | struct TEdge {
warning:       |        ^~~~~
warning: In file included from /nix/store/b3zsk4ihlpiimv3vff86bb5bxghgdzb9-gcc-9.2.0/include/c++/9.2.0/x86_64-unknown-linux-gnu/bits/os_defines.h:39,
warning:                  from /nix/store/b3zsk4ihlpiimv3vff86bb5bxghgdzb9-gcc-9.2.0/include/c++/9.2.0/x86_64-unknown-linux-gnu/bits/c++config.h:524,
warning:                  from /nix/store/b3zsk4ihlpiimv3vff86bb5bxghgdzb9-gcc-9.2.0/include/c++/9.2.0/cstdlib:41,
warning:                  from /nix/store/b3zsk4ihlpiimv3vff86bb5bxghgdzb9-gcc-9.2.0/include/c++/9.2.0/stdlib.h:36,
warning:                  from clipper/wrapper.h:8,
warning:                  from clipper/wrapper.cpp:1:
warning: /nix/store/fwpn2f7a4iqszyydw7ag61zlnp6xk5d3-glibc-2.30-dev/include/features.h:382:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
warning:   382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
warning:       |    ^~~~~~~
    Finished test [unoptimized + debuginfo] target(s) in 3.59s
```

**Comment by lelongg** [comment]
Compiling in release mode avoid optimization related warnings, this is what remains.
edit: I fixed these warnings by editing clipper.cpp, but I'm not really sure what is the best way to fix optimization warnings in debug mode...

```
warning: clipper/clipper.cpp: In function ‘ClipperLib::Int128 ClipperLib::Int128Mul(ClipperLib::long64, ClipperLib::long64)’:
warning: clipper/clipper.cpp:376:22: warning: implicitly-declared ‘constexpr ClipperLib::Int128& ClipperLib::Int128::operator=(const ClipperLib::Int128&)’ is deprecated [-Wdeprecated-copy]
warning:   376 |   if (negate) tmp = -tmp;
warning:       |                      ^~~
warning: clipper/clipper.cpp:264:5: note: because ‘ClipperLib::Int128’ has user-provided ‘ClipperLib::Int128::Int128(const ClipperLib::Int128&)’
warning:   264 |     Int128(const Int128 &val): lo(val.lo), hi(val.hi){}
warning:       |     ^~~~~~
warning: clipper/clipper.cpp: In function ‘void ClipperLib::InitEdge(ClipperLib::TEdge*, ClipperLib::TEdge*, ClipperLib::TEdge*, const ClipperLib::IntPoint&)’:
warning: clipper/clipper.cpp:721:34: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct ClipperLib::TEdge’; use assignment or value-initialization instead [-Wclass-memaccess]
warning:   721 |   std::memset(e, 0, sizeof(TEdge));
warning:       |                                  ^
warning: clipper/clipper.cpp:66:8: note: ‘struct ClipperLib::TEdge’ declared here
warning:    66 | struct TEdge {
warning:       |        ^~~~~
```

**Comment by jsadusk** [comment]
Nice! It gives no warnings for me now. Thanks!

**Comment by lelongg** [comment]
Ok, I will ignore the warnings related to optimization I get in debug mode for now and merge

**Pull request merged**
