### PR TITLE
Move bindgen from build.rs to a separate binary

### PR DESCRIPTION
**Pull request by kabergstrom**
Bindgen requires installing libclang on the building machine which is quite a heavy dependency to lug around. Fortunately, bindgen only needs to be run when the API bindings change as a result of the clipper API surface changing, and this is probably okay to do manually. I moved the bindgen code from `build.rs` to a `binding-gen` binary.

I also encountered a compile error with `uint` not being declared in `wrapper.cpp` which is also in this PR.

### CODE REVIEW

**Comment by kabergstrom** [comment]
aaand I just noticed #7 already exists. 😫

**Comment by lelongg** [comment]
Do you or @turnage know if there is a way to switch this on based on a cargo feature ?

**Comment by kabergstrom** [comment]
> Do you or @turnage know if there is a way to switch this on based on a cargo feature ?

Yes you can use Cargo optional dependencies: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html
and #[cfg(feature = "..")]

**Comment by lelongg** [comment]
Generated bindings is now shipped with source. You can use a generated one with `cargo build --features generate-bindings` and update the binding in sources with `cargo build --features update-bindings`

**Pull request closed without merging**
